### ISSUE TITLE
While problems (Function expression as block Condition)

### ISSUE THREAD

**Issue by NetLamp-Y** [ccldev/ccl-v2-tiny#2]
Code:
```
var condition = true;
while( {|| return condition;} ){
    println(condition);
    condition = false;
};
```
Exception at compile time:
```
Exception in thread "main" java.lang.RuntimeException: Oops, something you used should work without seeing this message.
Please notice the developer about it! Code:
while( {|| return condition;} ){
println(condition);
condition = false;
}
        at ccl.v2_1.debug.DebugHelper.consume(DebugHelper.java:28)
        at ccl.v2_1.debug.DebugHelper.consume(DebugHelper.java:30)
        at ccl.csy.CCL.compile(CCL.java:66)
        at ccl.csy.CCL.compile(CCL.java:37)
        at ccl.dev.test.TESt.main(TESt.java:92)
Caused by: ccl.v2_1.err.ImplementationException: java.lang.RuntimeException: Please check out the following code part:
;
        ... 4 more
Caused by: java.lang.RuntimeException: Please check out the following code part:
;
        at ccl.v2_1.debug.DebugHelper.consume(DebugHelper.java:22)
        at ccl.csy.CCL.compile(CCL.java:66)
        at ccl.csy.CCL.compile(CCL.java:37)
        at ccl.csy.FinisherImpl.finish(FinisherImpl.java:36)
        at ccl.v2_1.compile.Finisher.finish(Finisher.java:18)
        at ccl.csy.block.ControlBlockSystem.compileComplete(ControlBlockSystem.java:42)
        at ccl.csy.block.ControlBlockSystem.compileComplete(ControlBlockSystem.java:15)
        at io.github.coalangsoft.cclproject.CompileSystemUser.get(CompileSystemUser.java:32)
        at io.github.coalangsoft.cclproject.cat.CclCodeBlock.compile(CclCodeBlock.java:59)
        at ccl.v2_1.code.CclCodePart.compile(CclCodePart.java:28)
        at ccl.csy.CCL.compile(CCL.java:60)
        ... 2 more
Caused by: ccl.v2_1.err.DebugException: A value may not be empty!
        at ccl.csy.value.ValueCompiler.act(ValueCompiler.java:22)
        at ccl.csy.StaticValueCompiler.compileValue(StaticValueCompiler.java:11)
        at ccl.csy.DefaultSystem.compileComplete(DefaultSystem.java:22)
        at ccl.csy.DefaultSystem.compileComplete(DefaultSystem.java:12)
        at io.github.coalangsoft.cclproject.CompileSystemUser.get(CompileSystemUser.java:32)
        at io.github.coalangsoft.cclproject.cat.CclCodeSnippet.compile(CclCodeSnippet.java:27)
        at ccl.v2_1.code.CclCodePart.compile(CclCodePart.java:30)
        at ccl.csy.CCL.compile(CCL.java:60)
        ... 11 more
```
Working Code:
```
var condition = true;
var func = {|| return condition;};
while( func ){
    println(condition);
    condition = false;
};
```
Version 0.5.2.1

**Comment by NetLamp-Y** [comment]
Seemingly the `A value may not be empty!` exception is thrown when there is a wrong semicolon inserted by the compiler. So I removed the semicolon insertion for testing. Then I tried this code:
```
while({||}){
    println(c);
};
```
The compile result was:
```
load while
load read
__invoke0
__invoke1
putM _b0_.cl0
__invoke1
nnr2
```
So, except the Semicolon-Error, there is yet another: The compiler for the while-Loop is not getting a correct block condition.

**Comment by NetLamp-Y** [comment]
Found the problem in the second post: The general block parser used the `{` char to start a block. Of course this does not work with `{||}` as a condition. So I tried to rewrite the block parser in a way that allows `{}` in the condition. So the problem from post 2 is fixed, and the original one is too (same fix).
